### ISSUE TITLE
Wrong error message for function call

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-shell#276]
When following the readme in near-bindgen cross contract example https://github.com/nearprotocol/near-bindgen/tree/master/examples/cross-contract-high-level, at this step
```
near call cross_contract simple_call "{\"account_id\": \"status_message\", \"message\":\"bonjour\"}" --accountId=test_near --gas 1000000000000000
```
near shell gives
```
Error:  ActionError: The used access key requires exactly one FunctionCall action
    at Object.parseRpcError (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/utils/rpc_errors.js:25:19)
    at Account.signAndSendTransaction (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/account.js:94:36)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async scheduleFunctionCall (/usr/local/lib/node_modules/near-shell/commands/call.js:29:34)
    at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  type: 'ActionError',
  index: 0
}
```
but the actual error I see from printing results in nearcore is `Failure(Action #0: Exceeded the prepaid gas.)`.

It could be a bug in nearcore or nearlib and we should transfer this issue when we have more insights into the issue.

**Comment by janedegtiareva** [comment]
Verified that this is fixed. 
Note that the original steps to reproduce are no longer valid (create account commands and gas values are out of date - filed an issue https://github.com/near/near-sdk-rs/issues/152)
