### ISSUE TITLE
Issues with default gas value in change functions

### ISSUE THREAD

**Issue by potatodepaulo** [near/near-shell#428]
**Describe the bug**
The default gas throws an error in shell.

**To Reproduce**
 using default gas:

```shell
> near call dev-1592597267682 bet '{"race_id": "test", "horse_id": "1", "amount": 10}' --account_id aguxez.testnet --amount "1" 
(node:6292) ExperimentalWarning: The fs.promises API is experimental
Using options: { accountId: 'aguxez.testnet',
  amount: '1',
  networkId: 'default',
  nodeUrl: 'https://rpc.testnet.near.org',
  contractName: 'dev-1592597267682',
  walletUrl: 'https://wallet.testnet.near.org',
  helperUrl: 'https://helper.testnet.near.org',
  useLedgerKey: '44\'/397\'/0\'/0\'/1\'',
  gas: '100000000000000',
  methodName: 'bet',
  args: '{"race_id": "test", "horse_id": "1", "amount": 10}',
  initialBalance: null }
Scheduling a call: dev-1592597267682.bet({"race_id": "test", "horse_id": "1", "amount": 10}) with attached 1 NEAR
[dev-1592597267682]: dev-1592596982120
Error:  { Error: Exceeded the prepaid gas
    at Object.parseRpcError (/home/aguxez/.nvm/versions/node/v10.16.0/lib/node_modules/near-shell/node_modules/near-api-js/lib/utils/rpc_errors.js:38:19)
    at Account.signAndSendTransaction (/home/aguxez/.nvm/versions/node/v10.16.0/lib/node_modules/near-shell/node_modules/near-api-js/lib/account.js:115:36)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'GasExceeded', index: 0 }
```

Using the max gas:

```shell
> near call dev-1592597267682 bet '{"race_id": "test", "horse_id": "1", "amount": 10}' --account_id aguxez.testnet --amount "1" --gas "10000000000000000"
(node:6444) ExperimentalWarning: The fs.promises API is experimental
Using options: { accountId: 'aguxez.testnet',
  amount: '1',
  gas: '10000000000000000',
  networkId: 'default',
  nodeUrl: 'https://rpc.testnet.near.org',
  contractName: 'dev-1592597267682',
  walletUrl: 'https://wallet.testnet.near.org',
  helperUrl: 'https://helper.testnet.near.org',
  useLedgerKey: '44\'/397\'/0\'/0\'/1\'',
  methodName: 'bet',
  args: '{"race_id": "test", "horse_id": "1", "amount": 10}',
  initialBalance: null }
Scheduling a call: dev-1592597267682.bet({"race_id": "test", "horse_id": "1", "amount": 10}) with attached 1 NEAR
[dev-1592597267682]: dev-1592596982120
[dev-1592597267682]: aguxez.testnet bet 10 ZEST on horse 1 in race test
... (external call error) 
```

**Expected behavior**
That the transaction works with default gas.

**Comment by potatodepaulo** [comment]
Figured this out thanks to @bowenwang1996
