### ISSUE TITLE
near build doesn't work if gulp is not installed globally

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-shell#93]
{
  networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com',
  initialBalance: 100000000
}
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)

**Comment by chadoh** [comment]
`near build` will be removed soon
